name: locket_clone
description: "Locket Clone"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.3
  camera: ^0.11.2+1
  permission_handler: ^11.3.1
  gal: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/

  uses-material-design: true
